conda env list
conda activate theapy39
pip install tensorflow
pip install tensorflow-gpu

In [ ]:
# %tensorflow_version 2.x  # this line is not required unless you are in a notebook

UsageError: Line magic function `%tensorflow_version` not found.


In [4]:
import tensorflow as tf  # now import the tensorflow module
print(tf.version)  # make sure the version is 2.x

<module 'tensorflow._api.v2.version' from '/opt/miniconda3/envs/theapy39/lib/python3.9/site-packages/tensorflow/_api/v2/version/__init__.py'>


### Creating Tensors


In [12]:
# Creating Tensors 定义变量
string = tf.Variable("this is a string", tf.string) 
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)
tf.rank(number)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

### Rank/Degree of Tensors

In [ ]:
# What we created above is a tensor of rank 0, also known as a scalar.
rank1_tensor = tf.Variable(["Test"], tf.string) 
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [18]:
# To determine the rank of a tensor we can call the following method. 打印维度，rank，秩
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [15]:
rank1_tensor = tf.Variable(["Test","Test2","Test3"], tf.string) # 这是个队列，rank仍为1
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

### Shape of Tensors

In [ ]:
# To get the shape of a tensor we use the shape attribute.
rank2_tensor.shape # 形状

TensorShape([2, 2])

In [ ]:
rank1_tensor.shape # 形状

TensorShape([3])

In [17]:
rank2_tensor = tf.Variable([["test", "ok","right"], ["test", "yes","wrong"]], tf.string)
rank2_tensor.shape # 形状

TensorShape([2, 3])

### Changing Shape

In [ ]:
tensor1 = tf.ones([1,2,3])  # tf.ones() creates a shape [1,2,3] tensor full of ones，从外到里一次是，1个，2个，3个，每个都是1
tensor2 = tf.reshape(tensor1, [2,3,1])  # reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3, -1])  # -1 tells the tensor to calculate the size of the dimension in that place
                                        # this will reshape the tensor to [3,2]，-1表示自动计算，这里是2*3=6，所以-1=6/3=2
                                                                             
# The numer of elements in the reshaped tensor MUST match the number in the original

In [20]:
print(tensor1)
print(tensor2)
print(tensor3)
# Notice the changes in shape

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


### Slicing Tensors

In [21]:
# Creating a 2D tensor
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

tensor = tf.Variable(matrix, dtype=tf.int32) 
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [24]:
# Now lets select some different rows and columns from our tensor

three = tensor[0,2]  # selects the 3rd element from the 1st row
print(three)  # -> 3

row1 = tensor[0]  # selects the first row
print(row1)

column1 = tensor[:, 0]  # selects the first column
print(column1)

row_2_and_4 = tensor[1::2]  # selects second and fourth row
print(row_2_and_4)

column_1_in_row_2_and_3 = tensor[1:3, 0]
print(column_1_in_row_2_and_3)


tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)
tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)
tf.Tensor([ 6 11], shape=(2,), dtype=int32)


### Types of Tensors

Variable,可以改变，一般用于模型的参数

Constant,不变的量

Placeholder,占位符，用于输入数据

SparseTensor,稀疏张量，用于表示稀疏矩阵


In [ ]:
with tf.Session() as sess: # creates a session using the default graph，默认使用当前图
    tensor.eval() # evaluates the tensor and returns the result，这里会返回tensor的值

AttributeError: module 'tensorflow' has no attribute 'Session'

In [30]:
t = tf.zeros([3,3,3,3])
t =tf.reshape(t,[81])
t =tf.reshape(t,[27,-1])
print(t)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(27, 3), dtype=float32)
