In [2]:
import numpy as np

## numpy的数组类型

In [2]:
array = [1,2,3,4,5]
type(array)

list

In [7]:
array+1

TypeError: can only concatenate list (not "int") to list

In [3]:
nparray=np.array([1,2,3,4,5])
nparray

array([1, 2, 3, 4, 5])

In [ ]:
# 格式
type(nparray)

numpy.ndarray

In [ ]:
# 元素间加固定值
nparray+1

array([2, 3, 4, 5, 6])

In [ ]:
# 元素间相加
nparray+nparray

array([ 2,  4,  6,  8, 10])

In [ ]:
# 元素间相乘
nparray*nparray

array([ 1,  4,  9, 16, 25])

## ndarray结构

In [11]:
list_=[1,2,3,4]

In [ ]:
# list转化为array
array_=np.array(list_)
array_

array([1, 2, 3, 4])

In [ ]:
array_.dtype
# array里面的数据类型

dtype('int64')

In [14]:
list_=[1,2,3,4.0]
array_=np.array(list_)
array_

array([1., 2., 3., 4.])

In [ ]:
array_.dtype
# 要求数据类型是相同的

dtype('float64')

In [ ]:
# array的size
array_.size

4

In [ ]:
# array的维度
array_.ndim

1

In [ ]:
# array的shape
array_.shape

In [ ]:
# array用0赋值
array_.fill(0)
array_

array([0., 0., 0., 0.])

## 索引和切片

In [20]:
list_=[1,2,3,4.0]
array_=np.array(list_)
array_ 

array([1., 2., 3., 4.])

In [ ]:
# array取某一个值
array_[0]

np.float64(1.0)

In [ ]:
# array取倒数某一个值
array_[-1]

np.float64(4.0)

In [ ]:
# array取一个区间
array_[0:2] #[*,*）

array([1., 2.])

In [25]:
array_[:-1]

array([1., 2., 3.])

In [26]:
array_[-3:] 

array([2., 3., 4.])

In [ ]:
array_ = np.array([[1,2,3],[4,5,6],[7,8,9]])
array_

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
array_.shape

(3, 3)

In [29]:
array_.size

9

In [ ]:
array_.ndim # 维度

2

In [31]:
array_[1,1]

np.int64(5)

In [ ]:
# array修改某一个值
array_[1,1]=10
array_

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [ ]:
array_[1] # 第二行

array([ 4, 10,  6])

In [ ]:
array_[:,1] # 第二列,:代表这一行全部值

array([ 2, 10,  8])

In [ ]:
array_[:,1:3] # 后两列

array([[ 2,  3],
       [10,  6],
       [ 8,  9]])

In [ ]:
# array取某几行、某几列
array_[0:2,1:3] # 前两行后两列

array([[ 2,  3],
       [10,  6]])

## array的赋值

In [ ]:
array2= array_ # 复制的是地址，改变后原始值也会改变
array2

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [42]:
array2[1,1]=100
array2

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [43]:
array_

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [ ]:
# 数组的复制， copy
array2 = array_.copy()
array2

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [46]:
array2[1,1]=999
array2

array([[  1,   2,   3],
       [  4, 999,   6],
       [  7,   8,   9]])

In [47]:
array_

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [ ]:
# 新建一定范围及步长的array
array_=np.arange(0,100)
array_

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [50]:
array_=np.arange(0,100,10)
array_

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# 新建mask，bool型的array
mask = np.array([0,1,0,6,2,1,0,1],dtype=bool)
mask

array([False,  True, False,  True,  True,  True, False,  True])

In [52]:
array_[mask]

IndexError: boolean index did not match indexed array along axis 0; size of axis is 10 but size of corresponding boolean axis is 8

In [53]:
mask = np.array([0,1,0,6,2,1,0,1,0,0],dtype=bool)
mask

array([False,  True, False,  True,  True,  True, False,  True, False,
       False])

In [ ]:
array_[mask] # mask为true的时候保留值，否则去掉

array([10, 30, 40, 50, 70])

In [55]:
# 构造随机数
random_array=np.random.rand(10)
random_array

array([0.24422018, 0.2778581 , 0.26435319, 0.12501697, 0.75456123,
       0.97935205, 0.06550229, 0.65368906, 0.73651698, 0.48208961])

In [ ]:
# 一个随机数
random_int=np.random.randint(0,1000)
random_int

549

In [ ]:
# 随机种子
np.random.seed(0)
# 正太分布矩阵normal，其中loc：均值，scale：标准差
# 10个样本，1个特征
X=np.random.normal(size=(10,1),scale=1)
X

array([[ 1.76405235],
       [ 0.40015721],
       [ 0.97873798],
       [ 2.2408932 ],
       [ 1.86755799],
       [-0.97727788],
       [ 0.95008842],
       [-0.15135721],
       [-0.10321885],
       [ 0.4105985 ]])

In [ ]:
# 添加正态分布噪声
# 原始信号
t = np.linspace(0, 1, 100)
signal = np.sin(2 * np.pi * 5 * t)
# 添加噪声
noisy_signal = signal + np.random.normal(0, 0.5, size=100)

In [121]:
np.zeros(3)

array([0., 0., 0.])

In [122]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [123]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## 维度，和、乘积、平均、最大最小

In [59]:
random_array=np.random.randint(1,7,size=(3,3))
random_array

array([[2, 5, 4],
       [5, 2, 5],
       [2, 6, 2]])

In [ ]:
# 求和
np.sum(random_array)

np.int64(33)

In [ ]:
np.sum(random_array,axis=0) # 按照整体

array([ 9, 13, 11])

In [ ]:
np.sum(random_array,axis=1) # 按照第二个维度，求和

array([11, 12, 10])

In [63]:
random_array=np.random.randint(1,7,size=(3,3,3))
random_array

array([[[2, 1, 6],
        [2, 5, 5],
        [6, 4, 6]],

       [[4, 2, 1],
        [2, 3, 4],
        [4, 2, 2]],

       [[6, 5, 2],
        [6, 5, 3],
        [2, 1, 6]]])

In [64]:
random_array.ndim

3

In [65]:
np.sum(random_array,axis=0)

array([[12,  8,  9],
       [10, 13, 12],
       [12,  7, 14]])

In [66]:
np.sum(random_array,axis=1)

array([[10, 10, 17],
       [10,  7,  7],
       [14, 11, 11]])

In [67]:
np.sum(random_array,axis=2)

array([[ 9, 12, 16],
       [ 7,  9,  8],
       [13, 14,  9]])

In [74]:
random_array=np.random.randint(1,5,size=(2,2))
random_array

array([[2, 1],
       [4, 4]])

In [ ]:
# 求乘积，所有元素想成
random_array.prod()

np.int64(32)

In [76]:
random_array.prod(axis=0)

array([8, 4])

In [77]:
random_array.prod(axis=1)

array([ 2, 16])

In [78]:
random_array.min()

np.int64(1)

In [79]:
random_array.min(axis=0)

array([2, 1])

In [80]:
random_array.argmin()

np.int64(1)

In [81]:
random_array.argmin(axis=0)

array([0, 0])

In [82]:
random_array.argmax(axis=0)

array([1, 1])

In [83]:
random_array.argmax()

np.int64(2)

In [84]:
random_array.mean()

np.float64(2.75)

In [85]:
random_array.mean(axis=0)

array([3. , 2.5])

## 排序、形状操作、转置

In [86]:
random_array=np.random.randint(1,8,size=(2,5))
random_array

array([[2, 1, 5, 4, 5],
       [7, 2, 2, 2, 4]])

In [87]:
np.sort(random_array)

array([[1, 2, 4, 5, 5],
       [2, 2, 2, 4, 7]])

In [88]:
np.sort(random_array,axis=0)

array([[2, 1, 2, 2, 4],
       [7, 2, 5, 4, 5]])

In [90]:
np.sort(random_array,axis=1) # 默认按最后一位排序

array([[1, 2, 4, 5, 5],
       [2, 2, 2, 4, 7]])

In [91]:
np.argsort(random_array)

array([[1, 0, 3, 2, 4],
       [1, 2, 3, 4, 0]])

In [92]:
random_array.shape

(2, 5)

In [94]:
random_array.shape=10
random_array

array([2, 1, 5, 4, 5, 7, 2, 2, 2, 4])

In [ ]:
random_array.shape=5,2 # 形状乘积不变
random_array

array([[2, 1],
       [5, 4],
       [5, 7],
       [2, 2],
       [2, 4]])

In [98]:
random_array=random_array.reshape(1,10) 
random_array

array([[2, 1, 5, 4, 5, 7, 2, 2, 2, 4]])

In [102]:
random_array=random_array.reshape(10) 
random_array

array([2, 1, 5, 4, 5, 7, 2, 2, 2, 4])

In [ ]:
random_array_2=random_array[np.newaxis,:] # 增加一个维度
random_array_2

array([[2, 1, 5, 4, 5, 7, 2, 2, 2, 4]])

In [104]:
random_array.ndim

1

In [105]:
random_array_2.ndim

2

In [106]:
random_array_2.shape

(1, 10)

In [107]:
random_array_2 = random_array[np.newaxis,:,np.newaxis]
random_array_2

array([[[2],
        [1],
        [5],
        [4],
        [5],
        [7],
        [2],
        [2],
        [2],
        [4]]])

In [108]:
random_array_2.shape

(1, 10, 1)

In [109]:
random_array_2=random_array_2.squeeze()
random_array_2

array([2, 1, 5, 4, 5, 7, 2, 2, 2, 4])

In [110]:
random_array_2.shape

(10,)

In [112]:
random_array_2.shape=5,2
random_array_2

array([[2, 1],
       [5, 4],
       [5, 7],
       [2, 2],
       [2, 4]])

In [113]:
random_array_2.T

array([[2, 5, 5, 2, 2],
       [1, 4, 7, 2, 4]])

## 矩阵的连接, 点积，叉乘，比较

In [114]:
array1=np.random.randint(10,size=(2,5))
array1

array([[0, 7, 4, 6, 2],
       [6, 4, 3, 0, 5]])

In [115]:
array2=np.random.randint(10,size=(2,5))
array2

array([[2, 8, 5, 3, 5],
       [5, 4, 4, 6, 2]])

In [ ]:
# 拼接
array3=np.concatenate((array1,array2))
array3

array([[0, 7, 4, 6, 2],
       [6, 4, 3, 0, 5],
       [2, 8, 5, 3, 5],
       [5, 4, 4, 6, 2]])

In [117]:
array3=np.concatenate((array1,array2),axis=0)
array3

array([[0, 7, 4, 6, 2],
       [6, 4, 3, 0, 5],
       [2, 8, 5, 3, 5],
       [5, 4, 4, 6, 2]])

In [118]:
array3=np.concatenate((array1,array2),axis=1)
array3

array([[0, 7, 4, 6, 2, 2, 8, 5, 3, 5],
       [6, 4, 3, 0, 5, 5, 4, 4, 6, 2]])

In [119]:
np.zeros(3)

array([0., 0., 0.])

In [120]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [127]:
x=np.arange(0,2)
y=np.arange(2,4)
x,y

(array([0, 1]), array([2, 3]))

In [128]:
x*y

array([0, 3])

In [ ]:
np.multiply(x,y) # 点积

array([0, 3])

In [ ]:
np.dot(x,y) # 矩阵乘法，叉乘

np.int64(3)

In [131]:
x=np.arange(0,6).reshape(2,3)
y=np.arange(0,6).reshape(3,2)
x,y

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([[0, 1],
        [2, 3],
        [4, 5]]))

In [ ]:
np.dot(x,y) # 叉乘

array([[10, 13],
       [28, 40]])

In [133]:
x=np.arange(0,6).reshape(2,3)
y=np.arange(0,6).reshape(2,3)
x,y

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([[0, 1, 2],
        [3, 4, 5]]))

In [ ]:
x==y # 比较

array([[ True,  True,  True],
       [ True,  True,  True]])

In [135]:
y[0,1]=5
y

array([[0, 5, 2],
       [3, 4, 5]])

In [136]:
x == y

array([[ True, False,  True],
       [ True,  True,  True]])

In [11]:
np.random.seed(180)
# 一个随机数
random_int=np.random.randint(0,4)
random_int

1